config/routes.rb
Rails.application.routes.draw do
  resources :jobs
  resources :companies
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
    has_many :jobs
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :company
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all

    @finance_companies = Company.where(industry: 'finance')
    @productivity_companies = Company.where(industry: 'productivity')
    @ecommerce_companies = Company.where(industry: 'ecommerce')
    @utility_companies = Company.where(industry: 'utility')

    # @companies_hiring = []
    # Company.all.each do |company|
    #   @companies_hiring << company if company.jobs.count > 0
    # end

    # ALl companies that have relationships to jobs
    # and then ensure companies aren't repeated with 'distinct'
    @companies_hiring = Company.all.joins(:jobs).distinct
    
    # Companies in finance and also hiring (intersection)
    @finance_companies_hiring = @finance_companies & @companies_hiring

    # Companies either in the eccomerce or utility industries (union)
    @ecommerce_or_utility_companies = @ecommerce_companies | @utility_companies

    # Companies not hiring (Hiring')
    @companies_not_hiring = Company.where.not(id: @companies_hiring )
    
    # Companies hiring excluding those in finance (difference)
    @non_finance_companies_hiring = @companies_hiring - @finance_companies
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :industry)
    end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all

    @xero = Company.where(name: 'Xero')
    @xero_jobs = Job.where(company: @xero)
    @atlassian = Company.where(name: 'Atlassian')
    @atlassian_jobs = Job.where(company: @atlassian)
    
    @front_end_jobs = Job.where(front_end: true)
    @back_end_jobs = Job.where(back_end: true)
    # Intersection
    @full_stack_jobs = @front_end_jobs & @back_end_jobs
    # Difference
    @i_hate_back_end_jobs = @jobs - @back_end_jobs
    # @i_hate_back_end_jobs = Job.where.not(back_end: true)

    # Union
    @xero_or_atlassian_jobs = @atlassian_jobs | @xero_jobs
    
    @finance_companies = Company.where(industry: 'finance')
    @finance_jobs = Job.where(company: @finance_companies)
    # Difference
    @non_finance_full_stack_jobs = @full_stack_jobs - @finance_jobs

    @javascript_jobs = Job.where('description LIKE ?', '%javascript%')
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:company_id, :front_end, :back_end, :title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/companies/_company.html.erb
<div>
  <strong><%= company.name %></strong> | 
  <%= company.industry %> | 
  <%= pluralize company.jobs.count, 'job' %>

</div>

app/views/companies/_form.html.erb
<%= form_with(model: company, local: true) do |form| %>
  <% if company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :company_name %>
  </div>

  <div class="field">
    <%= form.label :industry %>
    <%= form.text_field :industry, id: :company_industry %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Companies</h1>
<h2>All</h2>
  <%= render @companies %>

  <h2>Finance</h2>
  <%= render @finance_companies %>

  <h2>Productivity</h2>
  <%= render @productivity_companies %>

  <h2>Ecommerce</h2>
  <%= render @ecommerce_companies %>

  <h2>Hiring</h2>
  <%= render @companies_hiring %>

  <h2>Not Hiring (Hiring')</h2>
  <%= render @companies_not_hiring %>

  <h2>Finance &#8745; Hiring</h2>
  <%= render @finance_companies_hiring %>

  <h2>Ecommerce &#8746; Utility</h2>
  <%= render @ecommerce_or_utility_companies %>

  <h2>None finance companies &#8745; Hiring</h2>
  <%= render @non_finance_companies_hiring %>
  

  
  
<br>
<%= link_to 'New Company', new_company_path %>

app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @company.name %>
</p>

<p>
  <strong>Industry:</strong>
  <%= @company.industry %>
</p>

<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>

app/views/jobs/_form.html.erb
<%= form_with(model: job, local: true) do |form| %>
  <% if job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :company_id %>
    <%= form.text_field :company_id, id: :job_company_id %>
  </div>

  <div class="field">
    <%= form.label :front_end %>
    <%= form.check_box :front_end, id: :job_front_end %>
  </div>

  <div class="field">
    <%= form.label :back_end %>
    <%= form.check_box :back_end, id: :job_back_end %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :job_title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :job_description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/jobs/_job.html.erb
<div>
  <h3><%= job.title %></h3>
  <h4><%= job.company.name %></h4>
  <p>
    <%= job.front_end ? 'front-end' : '' %>
    <%= job.back_end ? 'back-end' : '' %>
  </p>
  <p><%= job.description %></p>
</div>

app/views/jobs/edit.html.erb
<h1>Editing Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Jobs</h1>

<details>
  <summary>
    <h2>All</h2>
  </summary> 
  <%= render @jobs %>
</details>

<details>
  <summary>
    <h2>At Xero</h2>
  </summary>
    <%= render @xero_jobs %>
</details>

<details>
  <summary>
    <h2>Front-End Jobs</h2>
  </summary> 
    <%= render @front_end_jobs %>
</details>

<details>
  <summary>
    <h2>Full Stack Jobs (Front End ^ Back End)</h2>
  </summary> 
    <%= render @full_stack_jobs %>
</details>

<details>
  <summary>
    <h2>I hate back-end (back-end')</h2>
  </summary> 
    <%= render @i_hate_back_end_jobs %>
</details>

<details>
  <summary>
    <h2>Xero or Atlassian (Atlassion Jobs U Xero Jobs)</h2>
  </summary> 
    <%= render @xero_or_atlassian_jobs %>
</details>

<details>
  <summary>
    <h2>Non finance full stack jobs(Full Stack - finance jobs)</h2>
  </summary> 
    <%= render @non_finance_full_stack_jobs %>
</details>


<details>
  <summary>
    <h2>Javascript</h2>
  </summary> 
    <%= render @javascript_jobs %>
</details>
<br>

<%= link_to 'New Job', new_job_path %>

app/views/jobs/new.html.erb
<h1>New Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Company:</strong>
  <%= @job.company %>
</p>

<p>
  <strong>Front end:</strong>
  <%= @job.front_end %>
</p>

<p>
  <strong>Back end:</strong>
  <%= @job.back_end %>
</p>

<p>
  <strong>Title:</strong>
  <%= @job.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @job.description %>
</p>

<%= link_to 'Edit', edit_job_path(@job) %> |
<%= link_to 'Back', jobs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JobsRUs</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>